pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('pizzas/', views.pizzas, name = 'pizzas'),
    path('<int:pizza_id>/toppings/', views.toppings, name = 'toppings'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
 
    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.name

pizzas/views.py
from django.shortcuts import render
from .models import Pizza, Topping 

def index(request):
        return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()
    context = {'pizzas' : pizzas}
    return render (request, 'pizzas/pizzas.html', context)

def toppings(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    toppings = pizza.topping_set.order_by()
    context = {'pizza' : pizza, 'toppings' : toppings}
    return render (request, 'pizzas/toppings.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

<p>Pizzeria is your one stop shop for all your pizza needs.</p>
{% block content %}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content  %}

{% endblock content  %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}
{% block content %}
    <p>Pizzas</p>

    <ul>
        {% for pizza in pizzas %}
            <a href="{% url 'pizzas:toppings' pizza.id %}">{{ pizza }}</a>
            <p></p>
        {% empty %}
            <li>No pizzas have been added yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}

pizzas/templates/pizzas/toppings.html
{% extends "pizzas/base.html" %}

{% block content %}
    <p>Pizza: {{ pizza }}</p>

    <ul>
        {% for topping in toppings %}
            <li>{{ topping }}</li>
        {% empty %}
            <li>No toppings have been added yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}